/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PlatformRouteRouteImport } from './routes/platform/route'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedAcademicsRouteImport } from './routes/_authenticated/academics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform/analytics'
import { Route as PlatformPeopleRouteImport } from './routes/platform/people'
import { Route as PlatformPermissionsRouteImport } from './routes/platform/permissions'
import { Route as AuthenticatedMarksIndexRouteImport } from './routes/_authenticated/marks.index'
import { Route as AuthenticatedMarksSheetIdRouteImport } from './routes/_authenticated/marks.$sheetId'
import { Route as PlatformInstitutionsIndexRouteImport } from './routes/platform/institutions.index'
import { Route as PlatformInstitutionsInstitutionIdRouteImport } from './routes/platform/institutions.$institutionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademicsRoute = AuthenticatedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPeopleRoute = PlatformPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPermissionsRoute = PlatformPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const AuthenticatedMarksIndexRoute = AuthenticatedMarksIndexRouteImport.update({
  id: '/marks/',
  path: '/marks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksSheetIdRoute =
  AuthenticatedMarksSheetIdRouteImport.update({
    id: '/marks/$sheetId',
    path: '/marks/$sheetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PlatformInstitutionsIndexRoute =
  PlatformInstitutionsIndexRouteImport.update({
    id: '/institutions/',
    path: '/institutions/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformInstitutionsInstitutionIdRoute =
  PlatformInstitutionsInstitutionIdRouteImport.update({
    id: '/institutions/$institutionId',
    path: '/institutions/$institutionId',
    getParentRoute: () => PlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/pricing': typeof PricingRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/users': typeof AuthenticatedUsersRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/people': typeof PlatformPeopleRoute
  '/platform/permissions': typeof PlatformPermissionsRoute
  '/platform/': typeof PlatformIndexRoute
  '/marks/$sheetId': typeof AuthenticatedMarksSheetIdRoute
  '/platform/institutions/$institutionId': typeof PlatformInstitutionsInstitutionIdRoute
  '/marks/': typeof AuthenticatedMarksIndexRoute
  '/platform/institutions/': typeof PlatformInstitutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/pricing': typeof PricingRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/users': typeof AuthenticatedUsersRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/people': typeof PlatformPeopleRoute
  '/platform/permissions': typeof PlatformPermissionsRoute
  '/platform': typeof PlatformIndexRoute
  '/marks/$sheetId': typeof AuthenticatedMarksSheetIdRoute
  '/platform/institutions/$institutionId': typeof PlatformInstitutionsInstitutionIdRoute
  '/marks': typeof AuthenticatedMarksIndexRoute
  '/platform/institutions': typeof PlatformInstitutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/academics': typeof AuthenticatedAcademicsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/people': typeof PlatformPeopleRoute
  '/platform/permissions': typeof PlatformPermissionsRoute
  '/platform/': typeof PlatformIndexRoute
  '/_authenticated/marks/$sheetId': typeof AuthenticatedMarksSheetIdRoute
  '/platform/institutions/$institutionId': typeof PlatformInstitutionsInstitutionIdRoute
  '/_authenticated/marks/': typeof AuthenticatedMarksIndexRoute
  '/platform/institutions/': typeof PlatformInstitutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/auth'
    | '/contact'
    | '/platform-admin'
    | '/pricing'
    | '/academics'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/exams'
    | '/onboarding'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/students'
    | '/team'
    | '/users'
    | '/platform/analytics'
    | '/platform/people'
    | '/platform/permissions'
    | '/platform/'
    | '/marks/$sheetId'
    | '/platform/institutions/$institutionId'
    | '/marks/'
    | '/platform/institutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/platform-admin'
    | '/pricing'
    | '/academics'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/exams'
    | '/onboarding'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/students'
    | '/team'
    | '/users'
    | '/platform/analytics'
    | '/platform/people'
    | '/platform/permissions'
    | '/platform'
    | '/marks/$sheetId'
    | '/platform/institutions/$institutionId'
    | '/marks'
    | '/platform/institutions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/platform'
    | '/auth'
    | '/contact'
    | '/platform-admin'
    | '/pricing'
    | '/_authenticated/academics'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/exams'
    | '/_authenticated/onboarding'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/team'
    | '/_authenticated/users'
    | '/platform/analytics'
    | '/platform/people'
    | '/platform/permissions'
    | '/platform/'
    | '/_authenticated/marks/$sheetId'
    | '/platform/institutions/$institutionId'
    | '/_authenticated/marks/'
    | '/platform/institutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PlatformAdminRoute: typeof PlatformAdminRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academics': {
      id: '/_authenticated/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AuthenticatedAcademicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/people': {
      id: '/platform/people'
      path: '/people'
      fullPath: '/platform/people'
      preLoaderRoute: typeof PlatformPeopleRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/permissions': {
      id: '/platform/permissions'
      path: '/permissions'
      fullPath: '/platform/permissions'
      preLoaderRoute: typeof PlatformPermissionsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_authenticated/marks/': {
      id: '/_authenticated/marks/'
      path: '/marks'
      fullPath: '/marks/'
      preLoaderRoute: typeof AuthenticatedMarksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks/$sheetId': {
      id: '/_authenticated/marks/$sheetId'
      path: '/marks/$sheetId'
      fullPath: '/marks/$sheetId'
      preLoaderRoute: typeof AuthenticatedMarksSheetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/platform/institutions/': {
      id: '/platform/institutions/'
      path: '/institutions'
      fullPath: '/platform/institutions/'
      preLoaderRoute: typeof PlatformInstitutionsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/institutions/$institutionId': {
      id: '/platform/institutions/$institutionId'
      path: '/institutions/$institutionId'
      fullPath: '/platform/institutions/$institutionId'
      preLoaderRoute: typeof PlatformInstitutionsInstitutionIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicsRoute: typeof AuthenticatedAcademicsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedMarksSheetIdRoute: typeof AuthenticatedMarksSheetIdRoute
  AuthenticatedMarksIndexRoute: typeof AuthenticatedMarksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicsRoute: AuthenticatedAcademicsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedMarksSheetIdRoute: AuthenticatedMarksSheetIdRoute,
  AuthenticatedMarksIndexRoute: AuthenticatedMarksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteRouteChildren {
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformPeopleRoute: typeof PlatformPeopleRoute
  PlatformPermissionsRoute: typeof PlatformPermissionsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformInstitutionsInstitutionIdRoute: typeof PlatformInstitutionsInstitutionIdRoute
  PlatformInstitutionsIndexRoute: typeof PlatformInstitutionsIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformPeopleRoute: PlatformPeopleRoute,
  PlatformPermissionsRoute: PlatformPermissionsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformInstitutionsInstitutionIdRoute:
    PlatformInstitutionsInstitutionIdRoute,
  PlatformInstitutionsIndexRoute: PlatformInstitutionsIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PlatformAdminRoute: PlatformAdminRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
